openapi: 3.0.3
info:
  title: Arbitrage Scanner API
  description: API сканера арбитража криптовалют
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Локальный сервер разработки

paths:
  /arbitrage-opportunities/read:
    post:
      tags:
        - ArbitrageOpportunities
      summary: Получить список всех арбитражных возможностей
      operationId: readArbitrageOpportunities
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArbitrageOpportunityReadResponse'

components:
  schemas:

    # COMMON SCHEMAS

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: read
      discriminator:
        propertyName: requestType
        mapping:
          read: '#/components/schemas/ArbitrageOpportunityReadRequest'

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          read: '#/components/schemas/ArbitrageOpportunityReadResponse'

    ResponseResult:
      type: string
      enum:
        - success
        - error

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    ArbitrageOpportunity:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ArbitrageOpportunityId'
        tokenPair:
          type: string
          description: Торговая пара для арбитража
        buyExchange:
          type: string
          description: Биржа для покупки
        sellExchange:
          type: string
          description: Биржа для продажи
        buyPrice:
          type: number
          format: double
          description: Цена покупки
        sellPrice:
          type: number
          format: double
          description: Цена продажи
        priceDifference:
          type: number
          minimum: 0
          maximum: 100
          format: double
          description: Текущее расхождение цен в процентах
        status:
          $ref: '#/components/schemas/ArbitrageOpportunityStatus'

    ArbitrageOpportunityId:
      type: string
      description: Уникальный идентификатор арбитражной возможности
      example: "1893746293640137"

    ArbitrageOpportunityStatus:
      type: object
      description: Статус арбитражной возможности
      discriminator:
        propertyName: value
        mapping:
          active: "#/components/schemas/ActiveArbitrageOpportunityStatus"
          expired: "#/components/schemas/ExpiredArbitrageOpportunityStatus"
      oneOf:
        - $ref: '#/components/schemas/ActiveArbitrageOpportunityStatus'
        - $ref: '#/components/schemas/ExpiredArbitrageOpportunityStatus'

    ActiveArbitrageOpportunityStatus:
      type: object
      required: [ value, timestampStart ]
      properties:
        value:
          type: string
          enum: [ active ]
        timestampStart:
          type: integer
          format: int64
      example:
        value: active
        timestampStart: 1625247600

    ExpiredArbitrageOpportunityStatus:
      type: object
      required: [ value, timestampStart, timestampEnd ]
      properties:
        value:
          type: string
          enum: [ expired ]
        timestampStart:
          type: integer
          format: int64
        timestampEnd:
          type: integer
          format: int64
      example:
        value: expired
        timestampStart: 1625247600
        timestampEnd: 1625334000

    # RESPONSES

    ArbitrageOpportunityReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ArbitrageOpportunity'

    # REQUESTS
    ArbitrageOpportunityReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ArbitrageOpportunityId'

tags:
  - name: ArbitrageOpportunities
    description: Операции, связанные с арбитражем криптовалют