openapi: 3.0.3
info:
  title: Arbitrage Scanner API
  description: API сканера арбитража криптовалют
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Локальный сервер разработки

paths:
  /arbitrage-opportunities/read:
    post:
      tags:
        - ArbitrageOpportunities
      summary: Получить список всех арбитражных возможностей
      operationId: readArbitrageOpportunities
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArbitrageOpportunityObject'

components:
  schemas:
    #    ArbitrageOpportunitiesReadResponse:
    #      type: object
    #      properties:
    #        opportunities:
    #          type: array
    #          uniqueItems: true
    #          items:
    #            $ref: '#/components/schemas/ArbitrageOpportunityObject'
    #          description: Список арбитражных возможностей

    ArbitrageOpportunityStatus:
      type: object
      discriminator:
        propertyName: value
        mapping:
          active: "#/components/schemas/ActiveArbitrageOpportunityStatus"
          expired: "#/components/schemas/ExpiredArbitrageOpportunityStatus"
      oneOf:
        - $ref: '#/components/schemas/ActiveArbitrageOpportunityStatus'
        - $ref: '#/components/schemas/ExpiredArbitrageOpportunityStatus'

    ActiveArbitrageOpportunityStatus:
      type: object
      required: [ value, timestampStart ]
      properties:
        value:
          type: string
          enum: [ active ]
        timestampStart:
          type: integer
          format: int64

    ExpiredArbitrageOpportunityStatus:
      type: object
      required: [ value, timestampStart, timestampEnd ]
      properties:
        value:
          type: string
          enum: [ expired ]
        timestampStart:
          type: integer
          format: int64
        timestampEnd:
          type: integer
          format: int64

    ArbitrageOpportunityObject:
      type: object
      properties:
        id:
          type: string
          description: Уникальный идентификатор арбитражной возможности
        tokenPair:
          type: string
          description: Торговая пара для арбитража
        buyExchange:
          type: string
          description: Биржа для покупки
        sellExchange:
          type: string
          description: Биржа для продажи
        buyPrice:
          type: number
          format: double
          description: Цена покупки
        sellPrice:
          type: number
          format: double
          description: Цена продажи
        priceDifference:
          type: number
          minimum: 0
          maximum: 100
          format: double
          description: Текущее расхождение цен в процентах
        status:
          type: object
          description: Статус арбитражной возможности
          $ref: '#/components/schemas/ArbitrageOpportunityStatus'

tags:
  - name: ArbitrageOpportunities
    description: Операции, связанные с арбитражем криптовалют