openapi: 3.0.3
info:
  title: Arbitrage Scanner API
  description: API сканера арбитража криптовалют
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Локальный сервер разработки

paths:
  /arbitrage-opportunities/read:
    post:
      tags:
        - ArbitrageOpportunities
      summary: Получить арбитражную возможность
      operationId: readArbitrageOpportunities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArbitrageOpportunityReadRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArbitrageOpportunityReadResponse'

  /arbitrage-opportunities/search:
    post:
      tags:
        - ArbitrageOpportunities
      summary: Получить список арбитражных возможностей по фильтру
      operationId: searchArbitrageOpportunities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArbitrageOpportunitySearchRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArbitrageOpportunitySearchResponse'

  /arbitrage-opportunities/recalculate:
    post:
      tags:
        - ArbitrageOpportunities
      summary: Перерасчитать все арбитражные возможности
      operationId: recalculateArbitrageOpportunities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ArbitrageOpportunityRecalculateRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArbitrageOpportunityRecalculateResponse'

components:
  schemas:

    # COMMON SCHEMAS

    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: read
      discriminator:
        propertyName: requestType
        mapping:
          read: '#/components/schemas/ArbitrageOpportunityReadRequest'
          search: '#/components/schemas/ArbitrageOpportunitySearchRequest'
          recalculate: '#/components/schemas/ArbitrageOpportunityRecalculateRequest'

    IResponse:
      type: object
      description: Базовый интерфейс для всех ответов
      properties:
        responseType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
      discriminator:
        propertyName: responseType
        mapping:
          read: '#/components/schemas/ArbitrageOpportunityReadResponse'
          search: '#/components/schemas/ArbitrageOpportunitySearchResponse'
          recalculate: '#/components/schemas/ArbitrageOpportunityRecalculateResponse'

    ResponseResult:
      type: string
      enum:
        - success
        - error

    Error:
      type: object
      properties:
        code:
          type: string
        group:
          type: string
        field:
          type: string
        message:
          type: string

    CexPriceApi:
      type: object
      description: Агрегированные данные по цене с CEX
      properties:
        tokenId:
          $ref: '#/components/schemas/CexTokenIdApi'
        exchangeId:
          $ref: '#/components/schemas/CexExchangeIdApi'
        priceRaw:
          $ref: '#/components/schemas/CexPriceRawApi'

    CexTokenIdApi:
      type: string
      description: Уникальный идентификатор валюты на CEX

    CexExchangeIdApi:
      type: string
      description: Уникальный идентификатор CEX крипта биржи

    CexPriceRawApi:
      type: number
      description: Цена в "сырых" единицах (без учета делимости валюты)
      format: double

    CexToCexArbitrageOpportunityApi:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/ArbitrageOpportunityIdApi'
        cexTokenId:
          $ref: '#/components/schemas/CexTokenIdApi'
        buyCexExchangeId:
          $ref: '#/components/schemas/CexExchangeIdApi'
        sellCexExchangeId:
          $ref: '#/components/schemas/CexExchangeIdApi'
        buyCexPriceRaw:
          $ref: '#/components/schemas/CexPriceRawApi'
        sellCexPriceRaw:
          $ref: '#/components/schemas/CexPriceRawApi'
        spread:
          $ref: '#/components/schemas/ArbitrageOpportunitySpreadApi'
        timestampStart:
          type: integer
          format: int64
        timestampEnd:
          type: integer
          format: int64

    ArbitrageOpportunityIdApi:
      type: string
      description: Уникальный идентификатор арбитражной возможности
      example: "1893746293640137"

    ArbitrageOpportunitySpreadApi:
      type: number
      description: Спред арбитражной возможности
      minimum: 0
      maximum: 100
      format: double

    ArbitrageOpportunitySearchFilterApi:
      type: object
      description: Фильтр для поиска арбитражных возможностей
      properties:
        cexTokenIds:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CexTokenIdApi'
        cexExchangeIds:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CexExchangeIdApi'
        spread:
          $ref: '#/components/schemas/ArbitrageOpportunitySpreadApi'

    ArbitrageOpportunityMultiApi:
      allOf:
        - type: object
          description: Список найденных объектов
          properties:
            arbitrageOpportunities:
              type: array
              items:
                $ref: '#/components/schemas/CexToCexArbitrageOpportunityApi'

    ArbitrageOpportunityRequestDebugModeApi:
      type: string
      enum:
        - prod
        - test
        - stub

    ArbitrageOpportunityRequestDebugApi:
      type: object
      properties:
        debug:
          $ref: '#/components/schemas/ArbitrageOpportunityDebugApi'

    ArbitrageOpportunityDebugApi:
      type: object
      properties:
        mode:
          $ref: '#/components/schemas/ArbitrageOpportunityRequestDebugModeApi'
        stub:
          $ref: '#/components/schemas/ArbitrageOpportunityRequestDebugStubsApi'

    ArbitrageOpportunityRequestDebugStubsApi:
      type: string
      description: Перечисления всех стабов
      enum:
        - success
        - notFound
        - badId


    # RESPONSES

    ArbitrageOpportunityReadResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - type: object
          properties:
            arbitrageOpportunity:
              $ref: '#/components/schemas/CexToCexArbitrageOpportunityApi'

    ArbitrageOpportunitySearchResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - $ref: '#/components/schemas/ArbitrageOpportunityMultiApi'

    ArbitrageOpportunityRecalculateResponse:
      allOf:
        - $ref: '#/components/schemas/IResponse'
        - type: object
          properties:
            opportunitiesCount:
              type: integer
              description: Количество найденных арбитражных возможностей
              format: int32
            processingTimeMs:
              type: integer
              description: Время выполнения операции в миллисекундах
              format: int64

    # REQUESTS
    ArbitrageOpportunityReadRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ArbitrageOpportunityRequestDebugApi'
        - type: object
          properties:
            id:
              $ref: '#/components/schemas/ArbitrageOpportunityIdApi'

    ArbitrageOpportunitySearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ArbitrageOpportunityRequestDebugApi'
        - type: object
          properties:
            filter:
              $ref: '#/components/schemas/ArbitrageOpportunitySearchFilterApi'

    ArbitrageOpportunityRecalculateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - $ref: '#/components/schemas/ArbitrageOpportunityRequestDebugApi'

tags:
  - name: ArbitrageOpportunities
    description: Операции, связанные с арбитражем криптовалют